In [92]:
import pandas as pd
import requests 
import numpy as np

In [93]:
df=pd.read_csv('커피빈매장.csv')
df

          Name                           Address           Tel
0     삼성봉은사거리점             서울시 강남구 영동대로 607 1,2층  02-3443-5618
1    코엑스웨스틴서울점   서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드   02-569-3103
2      삼성오크우드점           서울 강남구 테헤란로87길 46 지하 2층  02-3466-8507
3      삼성봉은사로점           서울시 강남구 봉은사로 628 엘슨빌딩1층   02-538-4523
4      도심공항타워점        서울시 강남구 테헤란로87길 36 공항타워 1층  02-2016-5330
..         ...                               ...           ...
208  강동경희대병원앞점         서울특별시 강동구 동남로 885 양지빌딩 1층   02-481-9938
209      새문안로점       서울특별시 종로구 새문안로 91 고려빌딩 1,2층   02-739-5806
210  광화문역1번출구점           서울시 종로구 새문안로5가길 7 1층 일부   02-723-3360
211   성균관대법학관점   서울시 종로구 성균관로 25-2 성균관대학교 법학관 B2   02-740-1958
212    경희궁의아침점  서울시 종로구 새문안로3길 23 경희궁아침상가4단지105외   02-730-8896

[213 rows x 3 columns]

In [94]:
#csv 주소 토대로 좌표 받기(API)
def get_location(address):
    url="https://dapi.kakao.com/v2/local/search/address.json?query="+address #주소를 기반으로 좌표를 받기
    headers={"Authorization": 'KakaoAK e779cdef1331864a0977eaff9b2fed22'}
    res=requests.get(url,headers=headers).json()
    if res['documents']:
        x=res['documents'][0]['x']
        y=res['documents'][0]['y']
    else:
        x=np.nan
        y=np.nan
    return x, y #자료 받아오고 return 해줘야 함
    
    

x, y=get_location('서울시')
x, y

('126.978652258309', '37.5668260046608')

In [95]:
store=pd.read_csv('커피빈매장.csv')
store['X']=''
store['Y']=''
store.head(2)

        Name                          Address           Tel X Y
0   삼성봉은사거리점            서울시 강남구 영동대로 607 1,2층  02-3443-5618
1  코엑스웨스틴서울점  서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드   02-569-3103

In [105]:
for i in store.index:
    address=store.loc[i,'Address']
    x, y = get_location(address)
    print(x, y)
    store.loc[i,'X']=x
    store.loc[i,'Y']=y

nan nan
127.057115600619 37.5129534255276
127.058205573267 37.5109823973192
127.064164448221 37.5146694627537
127.058597240146 37.5102336492314
127.061023782931 37.510356849269
127.059443354483 37.5096322564759
127.06080691987 37.5091916919873
127.054150521266 37.5107115918746
127.058776738588 37.5070611225729
127.062895193334 37.5070873831686
127.058292440311 37.50589366006
127.050036555762 37.5199060766075
127.052402933477 37.5061948324582
127.056186481052 37.5045993053356
127.053159553826 37.5047428849251
127.047899800263 37.5056868654944
127.050586603895 37.5034040395308
127.042972144359 37.5102810924204
127.048914400159 37.503773975836
127.047232410937 37.5252547717564
127.044387474036 37.5244894827177
nan nan
nan nan
126.949787848373 37.5418967410602
nan nan
126.952183895644 37.4796070667241
126.972649439494 37.5769954696057
127.140977607565 37.4434253308098
nan nan
126.929697406323 37.5218090317976
126.929338616058 37.5242915298626
126.928066576601 37.5197460148873
126.927297465564 37.5248882861767
nan nan
126.924876706923 37.5251775245928
126.924586046016 37.522516139033
nan nan
126.924843194287 37.5307295655332
126.92508838544 37.5568275244158
126.923266632289 37.5554722456428
127.126360491293 37.4110208490997
127.125978531405 37.4095029491435
126.903715993779 37.5172332566615
127.388960470639 36.3509886552386
127.025725359083 37.6390955501842
126.896538036905 37.4849270383011
127.223940331575 37.5454041231797
126.888212953215 37.5081230677129
126.88904246102 37.5196469645582
127.06017787506 37.6538310278932
126.921096166394 37.6004493355977
127.12523654354 37.3853420421398
126.886476789522 37.478720573213
127.112312363818 37.3781334075052
126.959414289663 37.3935078942772
126.875771989415 37.5281783139269
126.892773992481 37.5797159011058
126.892773992481 37.5797159011058
127.105603334255 37.3707082053063
126.887937496441 37.582468718569
126.947202895332 37.3724051471608
126.851250232655 37.5548546834697
126.880947375247 37.4171034624346
127.081689148468 37.5114162901687
127.055233195315 37.4966225187716
127.035957481795 37.5100538600899
127.037083772824 37.5237561531657
127.038182970834 37.5263370842465
127.039885329906 37.50102236437
127.034665821539 37.5078448024619
127.034714418284 37.5070324421316
127.036521514294 37.502349282282
127.029536928342 37.5159610912838
127.034897822252 37.500619211163
127.03648868939 37.4985735366506
127.034141792509 37.4990862800943
nan nan
127.041675092178 37.4922389145982
127.027426608456 37.524421297629
126.930982279358 37.3585078307294
126.826076887806 37.5629234842805
126.824695969186 37.5608751008131
126.813963062169 37.4614946950643
128.59879306028 35.8699830814753
127.002952238108 37.30508998386
126.832991977195 37.6317396610579
127.273684824487 37.65408246185
126.782823051713 37.4866835002109
127.050518820725 37.2906667925637
126.974164012539 37.2959770000514
127.095257911166 37.7448754366902
127.026459525531 37.2688010652736
127.202128029885 37.294066695953
127.0326839743 37.2649449442455
127.200511081391 37.2903638439839
127.000179930083 37.2655920786365
128.14576837039 35.1781697810343
nan nan
126.773131388502 37.6567152545134
126.772038816453 37.6558964094856
127.057572127932 37.2462246621025
128.654408692296 35.2396668440149
128.680810708184 35.2234911053458
127.02605222215 37.5055116110689
nan nan
127.032169064933 37.4961482913142
127.029260610601 37.4989136957534
127.025594068116 37.5045343907375
127.026069579038 37.5020858941495
127.027290827849 37.5001117846329
nan nan
127.022823344866 37.5068517133248
127.024880498727 37.5023574434123
127.027000294801 37.5318069076157
127.020431538347 37.5119461613615
127.025735420451 37.4985502394657
127.028208465188 37.4956734817567
127.045052231494 37.4855733712043
127.026914460572 37.4966333557707
127.025703589132 37.4967437284397
127.024516764632 37.4974340616184
127.03026231978 37.4912870511791
127.101225932288 37.5165777895252
127.101553183969 37.5070691238449
nan nan
127.095692162256 37.535725176732
129.008755219018 35.2240810071698
126.754526582068 37.6645540981816
129.082381897171 35.1854467005759
129.058041866196 35.1563071015735
129.129523260187 35.1688178394069
129.132817784816 35.1678106760758
129.036529466282 35.1067181869781
129.035685630449 35.098981097777
127.188439781762 37.2296433007505
nan nan
127.074679321062 37.2058406007355
127.069281504509 37.2048484896364
126.677577628872 37.6365009365146
126.736860627485 37.7294215154692
126.662841516858 37.3786608661181
126.656372166201 37.3802255186684
126.686213843644 37.7063244875731
127.034949554107 37.4827666361943
127.09489656845 37.53985699394
127.10796656942 37.5145543838088
127.015601806503 37.4987321235919
127.011825492621 37.5003183328671
127.013538414144 37.4956330957501
127.112781230361 37.5169302452841
127.104115178497 37.4887766507842
126.813524514918 37.1593983647558
126.527560680131 33.5128730968875
126.534540530554 33.4844445262988
126.813524514918 37.1593983647558
126.813524514918 37.1593983647558
126.363585353938 33.4780630755235
nan nan
127.015576900888 37.4855373251844
127.10293064906 37.5441340657514
127.010531864513 37.486696128715
127.04013984355 37.4690084600597
126.998481292627 37.5348144623725
126.491489796733 37.4934207705586
126.43320918812 37.4692488244219
126.427699293474 37.458350712273
127.11150165951 37.0004682235819
126.993107501389 37.5285655568387
127.128015153134 37.524564226881
127.070501006018 37.570948129697
127.12100938212 37.4860552797801
127.122198444997 37.4836465628118
127.124979804141 37.4796870553794
126.985532367698 37.4957101117888
nan nan
127.720054731926 37.8665963452691
127.927649555629 37.345730271733
126.985707093498 37.5614599246316
126.966653789116 37.5288173852679
nan nan
126.964741503485 37.5297718014452
127.026248862202 37.5873771473625
126.985010733916 37.5651546444578
126.974048614143 37.5543029383069
nan nan
126.988409831075 37.5698794886241
126.973751343837 37.555503632236
126.98132044403 37.5643288057316
126.984507517226 37.5678035976862
127.003706808109 37.5814020979301
126.981865819602 37.5664918220199
126.981865819602 37.5664918220199
126.985169386018 37.56991129156
127.981662850501 37.3233830428989
nan nan
126.987334399767 37.5730079037521
126.975593964647 37.5623085377513
126.979375711608 37.5670466069498
126.983530268891 37.5716808092144
126.972035325682 37.5602669008102
127.001154914843 37.5835220981147
126.977592007714 37.5690748736876
126.97825653257 37.5684232177354
127.084792605442 37.5964485466639
126.978860937689 37.5697855426617
126.979481465774 37.5718747898899
nan nan
127.155975988269 37.5526535932606
126.974761002545 37.5704876038354
126.974038245085 37.5727711995017
126.993115116294 37.5872284082508
126.972440824541 37.5726308227784

In [ ]:
store.isnull().sum()
store.dropna(inplace=True)
store.to_csv('커피빈맵.csv',index=False)

,Name,Address,Tel,X,Y
1,코엑스웨스틴서울점,서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드,02-569-3103,127.057115600619,37.5129534255276
2,삼성오크우드점,서울 강남구 테헤란로87길 46 지하 2층,02-3466-8507,127.058205573267,37.5109823973192
3,삼성봉은사로점,서울시 강남구 봉은사로 628 엘슨빌딩1층,02-538-4523,127.064164448221,37.5146694627537
4,도심공항타워점,서울시 강남구 테헤란로87길 36 공항타워 1층,02-2016-5330,127.058597240146,37.5102336492314
5,트레이드타워점,서울시 강남구 영동대로 511 트레이드타워 지하1층,02-803-9994,127.061023782931,37.510356849269
...,...,...,...,...,...
208,강동경희대병원앞점,서울특별시 강동구 동남로 885 양지빌딩 1층,02-481-9938,127.155975988269,37.5526535932606
209,새문안로점,"서울특별시 종로구 새문안로 91 고려빌딩 1,2층",02-739-5806,126.974761002545,37.5704876038354
210,광화문역1번출구점,서울시 종로구 새문안로5가길 7 1층 일부,02-723-3360,126.974038245085,37.5727711995017
211,성균관대법학관점,서울시 종로구 성균관로 25-2 성균관대학교 법학관 B2,02-740-1958,126.993115116294,37.5872284082508
212,경희궁의아침점,서울시 종로구 새문안로3길 23 경희궁아침상가4단지105외,02-730-8896,126.972440824541,37.5726308227784

In [ ]:
address='서울시 강남구'
filt=store['Address'].str.contains(address)
df= store[filt]
store=pd.read_csv('커피빈맵.csv',index_col=False)

                 Name                             Address           Tel X Y
0            삼성봉은사거리점               서울시 강남구 영동대로 607 1,2층  02-3443-5618
1           코엑스웨스틴서울점     서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드   02-569-3103
3             삼성봉은사로점             서울시 강남구 봉은사로 628 엘슨빌딩1층   02-538-4523
4             도심공항타워점          서울시 강남구 테헤란로87길 36 공항타워 1층  02-2016-5330
5             트레이드타워점        서울시 강남구 영동대로 511 트레이드타워 지하1층   02-803-9994
6               도심공항점      서울시 강남구 테헤란로87길22 도심공항터미널 지하1층   02-551-6456
7              파르나스몰점          서울시 강남구 테헤란로521 파르나스몰 지하1층   02-538-2008
8                삼성로점               서울시 강남구 삼성로 551 1층,2층   02-552-9311
10         삼성역글라스타워뒷점      서울시 강남구 영동대로85길 9 (대치동) 서전빌딩1층   02-552-3363
12              청담성당점           서울시 강남구 삼성로 716 LEE76빌딩2층   02-542-2053
13       선릉KSA한국표준협회점          서울시 강남구 테헤란로69길 5 DT센터점 1층  02-3141-7948
15         테헤란로하이닉스뒷점              서울시 강남구 테헤란로 70길 12 1층   02-538-9927
16            선릉로93길점            서울시 강남구 선릉로93길 6(역삼동) 1층   02-552-3177
17            선릉로86길점                   서울시 강남구 선릉로86길 11  02-2051-8875
18              선정릉역점        서울시 강남구 봉은사로 331 SH빌딩점 B1-1층  02-2058-3028
20              청담에스점   서울시 강남구 압구정로 461 네이처포엠빌딩B108,109호   02-548-6052
21              청담카페점          서울시 강남구 도산대로 67길 7,파크빌딩 1층   02-514-5622
22          테헤란로비젼타워점          서울시 강남구 테헤란로 312 707-2번지1층   02-558-7101
23              영동고앞점                서울시 강남구 선릉로 749 1,2층   02-544-3794
66            논현팍스타워점         서울시 강남구 논현 231-13호 팍스타워지하1층   02-513-3870
67             압구정시티점        서울시 강남구 도산대로49길 13 1층 17,18호   02-543-5922
69           역삼동태광타워점         서울시 강남구 역삼동 718-20  태광타워 1층   02-569-9867
70            차병원사거리점              서울시 강남구 봉은사로207 KJ타워1층   02-542-8813
71               차병원점             서울시 강남구 논현로 566 강남차병원1층   02-538-7615
72                역삼점             서울시 강남구 논현로 512  지상1,2층   02-569-8051
73           논현동수면센터점                  서울시 강남구 논현로 717 1층  02-3443-5575
74           역삼역4번출구점              서울시 강남구 테헤란로143 고운빌딩1층   02-508-1137
75   역삼KSA한국표준협회교육센터점                서울시 강남구 역삼동 738번지 1층   02-488-5912
76          역삼포스틸타워뒷점         서울시 강남구 테헤란로 20길 10 쓰리엠타워1층   02-554-9962
79              뉴압구정점         서울시 강남구 논현로 167길 9 낙산프라자 1층   02-545-3181
105               도곡점  서울시 강남구 언주로 30길 10,112 현대비젼21 112호   02-572-2781
106           국기원사거리점               서울시 강남구 테헤란로 8길 42 1층   02-552-7106
109           강남대로센터점           서울시 강남구 강남대로442 흥국화재빌딩 2층   02-565-3345
110          강남역먹자골목점       서울시 강남구 테헤란로1길 29 1층일부 및 2.3층   02-552-6311
111         강남역랭기지타워점        서울시 강남구 테헤란로4길 28 826-28호 1층   02-563-3655
114         압구정현대아파트점              서울시 강남구 압구정로29길65 지하1층   02-518-3350
118              매봉역점             서울시 강남구 논현로 38길 42 418호   02-529-9947

In [158]:
import folium #지도 만드는 함수(진짜 맵)
import warnings



def get_map(address):
    filt=store['Address'].str.contains(address)
    df=store[filt]
    if len(df.index)==0:
        print('없음')
    else:
        first=df.head(1) #첫번째 데이터 가져오기
        x=first['X']
        y=first['Y']
        map=folium.Map(location=[y,x], zoom_start=15) #맵을 형성하며, 위치는 y x로 초기 크기는 15로 지정 
        for idx, row in df.iterrows():
            head=row['Name']
            x=row['X']
            y=row['Y']
            folium.Marker(location=[y,x],popup=folium.Popup(f'{idx},{head}', max_width=200), icon=folium.Icon(icon_color='purple',icon='triangle')).add_to(map)
        map.save(f'{address}.html')       
        print('있음')
get_map('서울')

있음

c:\Users\AIPM2\AppData\Local\Programs\Python\Python310\lib\site-packages\folium\utilities.py:103: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  float(coord)
c:\Users\AIPM2\AppData\Local\Programs\Python\Python310\lib\site-packages\folium\utilities.py:109: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  if math.isnan(float(coord)):
c:\Users\AIPM2\AppData\Local\Programs\Python\Python310\lib\site-packages\folium\utilities.py:111: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return [float(x) for x in coords]

,Name,Address,Tel,X,Y
1,코엑스웨스틴서울점,서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드,02-569-3103,127.057115600619,37.5129534255276
2,삼성오크우드점,서울 강남구 테헤란로87길 46 지하 2층,02-3466-8507,127.058205573267,37.5109823973192
3,삼성봉은사로점,서울시 강남구 봉은사로 628 엘슨빌딩1층,02-538-4523,127.064164448221,37.5146694627537
4,도심공항타워점,서울시 강남구 테헤란로87길 36 공항타워 1층,02-2016-5330,127.058597240146,37.5102336492314
5,트레이드타워점,서울시 강남구 영동대로 511 트레이드타워 지하1층,02-803-9994,127.061023782931,37.510356849269
...,...,...,...,...,...
208,강동경희대병원앞점,서울특별시 강동구 동남로 885 양지빌딩 1층,02-481-9938,127.155975988269,37.5526535932606
209,새문안로점,"서울특별시 종로구 새문안로 91 고려빌딩 1,2층",02-739-5806,126.974761002545,37.5704876038354
210,광화문역1번출구점,서울시 종로구 새문안로5가길 7 1층 일부,02-723-3360,126.974038245085,37.5727711995017
211,성균관대법학관점,서울시 종로구 성균관로 25-2 성균관대학교 법학관 B2,02-740-1958,126.993115116294,37.5872284082508
212,경희궁의아침점,서울시 종로구 새문안로3길 23 경희궁아침상가4단지105외,02-730-8896,126.972440824541,37.5726308227784